name: 'dbt_bq_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_bq_project'

model-paths: ["dbt_bq_project/models"]
analysis-paths: ["dbt_bq_project/analyses"]
test-paths: ["dbt_bq_project/tests"]
seed-paths: ["dbt_bq_project/seeds"]
macro-paths: ["dbt_bq_project/macros"]
snapshot-paths: ["dbt_bq_project/snapshots"]

clean-targets:
  - "dbt_bq_project/target"
  - "dbt_bq_project/dbt_packages"

models:
  dbt_bq_project:
    materialized: table
      
